---   
---   

<h1 align="center">ExD</h1>
<h1 align="center">Course: Advanced Python Programming Language</h1>


---
<h3><div align="right">Instructor: Kiran Khursheed</div></h3>    

<h1 align="center">Pandas-03</h1>

<img align="right" width="400" height="400"  src="images/pandas-apps.png"  >

## _Overview of Pandas Dataframe Data Structure_

#### Read about Pandas Data Structures: https://pandas.pydata.org/docs/user_guide/dsintro.html#dsintro

## Learning agenda of this notebook
1. Anatomy of a Dataframe
2. Creating Dataframe
    - An empty dataframe
    - Two-Dimensional NumPy Array
    - Dictionary of Python Lists
    - Dictionary of Panda Series
2. Attributes of a Dataframe
3. Bonus

In [ ]:
# To install this library in Jupyter notebook
#import sys
#!{sys.executable} -m pip install pandas

In [1]:
import pandas as pd
pd.__version__ , pd.__path__

('1.3.4', ['C:\\Users\\Kiran\\anaconda3\\lib\\site-packages\\pandas'])

<img align="right" width="500" height="500"  src="images/pandas00.png"  >

## 1. Creating a Dataframe
<br><br>
>**A Pandas Dataframe is a two-dimensional labeled data structure (like SQL table) with heterogeneously typed columns, having both a row and a column index.**

<br><br><br><br>

**```pd.DataFrame(data=None, index=None, columns=None, dtype=None)```**
- Where,
   - `data`: It can be a 2-D NumPy Array, a Dictionary of Python Lists, or a Dictionary of Panda Series (You can also create a dataframe from a file in CSV, Excel, JSON, HTML format or may be from a database table as well).
   - `index`: These are the row indices. Will default to RangeIndex (0, 1, 2, ..., n), if index argument is not passed and no indexing information is part of input data.
   - `columns`: These are the column indices or labels. Will default to RangeIndex (0, 1, 2, ..., n), if index argument is not passed and no indexing information is part of input data.
   - `dtype`: Data type to force. Only a single dtype is allowed. If None, infer.

### a. Creating an Empty Dataframe

In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


### b. Creating a Dataframe from a 2-D NumPy Array

In [3]:
arr = np.random.randint(10,100, size= (6,5))
print("Numpy Array:\n",arr)

df = pd.DataFrame(data=arr)
print("Pandas Dataframe:\n",df)

Numpy Array:
 [[60 74 43 97 14]
 [25 30 20 97 96]
 [11 29 59 26 71]
 [49 93 64 41 47]
 [65 76 92 21 96]
 [18 95 91 53 20]]
Pandas Dataframe:
     0   1   2   3   4
0  60  74  43  97  14
1  25  30  20  97  96
2  11  29  59  26  71
3  49  93  64  41  47
4  65  76  92  21  96
5  18  95  91  53  20


- Note that both the row indices and the column labels/indices are implicitly set to numerical values from 0 to n-1, since neither of the two is provided while creating the dataframe object. They are also not considered as part of data in the dataframe.
- In majority of the cases the row label is left as default, i.e., 0,1,2,3.... However, the column labels are changed from 0,1,2,3,... to some meaningful values.

In [4]:
# Let us name the column labels of our choice, while creating it
col_labels=['Col1', 'Col2', 'Col3', 'Col4', 'Col5']
df = pd.DataFrame(data=arr, columns=col_labels)
df

Col1  Col2  Col3  Col4  Col5
0    60    74    43    97    14
1    25    30    20    97    96
2    11    29    59    26    71
3    49    93    64    41    47
4    65    76    92    21    96
5    18    95    91    53    20

In [5]:
# Let us name the row labels of our choice, while creating it
df = pd.DataFrame(data=arr, index=['Row0', 'Row1', 'Row2', 'Row3', 'Row4', 'Row5'])
df

0   1   2   3   4
Row0  60  74  43  97  14
Row1  25  30  20  97  96
Row2  11  29  59  26  71
Row3  49  93  64  41  47
Row4  65  76  92  21  96
Row5  18  95  91  53  20

In [6]:
# Let us name the both row labels and column labels to strings of our choice, while creating it
row_labels = ['Row0', 'Row1', 'Row2', 'Row3', 'Row4', 'Row5']
col_labels = ['Col0', 'Col1', 'Col2', 'Col3', 'Col4']
df = pd.DataFrame(data=arr, index=row_labels, columns=col_labels)
df

Col0  Col1  Col2  Col3  Col4
Row0    60    74    43    97    14
Row1    25    30    20    97    96
Row2    11    29    59    26    71
Row3    49    93    64    41    47
Row4    65    76    92    21    96
Row5    18    95    91    53    20

In [7]:
df['Row0']

KeyError: 'Row0'

- You can do this later as well, i.e., after the dataframe has been created with default indices.
- This is done by assigning a list of labels/values to `index` and `columns` attributes of a dataframe object.

In [ ]:
arr = np.random.randint(10,100, size= (6,5))
df = pd.DataFrame(data=arr)
df

In [ ]:
row_labels = ['Row0', 'Row1', 'Row2', 'Row3', 'Row4', 'Row5']
col_labels = ['Col0', 'Col1', 'Col2', 'Col3', 'Col4']

df.columns = col_labels
df.index = row_labels
df

### c. Creating a Dataframe from a Dictionary of Python Lists
- You can create a dataframe object from a dictionary of Python Lists 
    - The dictionary `Keys` become the column names, and 
    - The dictionary `Values` are lists/arrays containing data for the respective columns.

In [8]:
people = {
    "name" : ["Khursheed", "Aqsa", "Sana", "Wajeeha", "Basirat", "Hrm"],
    "age" : [52, 51, 26, 22, 18, 17],
    "address": ["Lahore", "Karachi", "Lahore", "Islamabad", "Kakul", "Karachi"],
    "cell" : ["321-123", "320-431", "321-478", "324-446", "321-967", "320-678"],
    "bg": ["B+", "A-", "B+", "O-", "A-", "B+"]
}
people

{'name': ['Khursheed', 'Aqsa', 'Sana', 'Wajeeha', 'Basirat', 'Hrm'],
 'age': [52, 51, 26, 22, 18, 17],
 'address': ['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Kakul', 'Karachi'],
 'cell': ['321-123', '320-431', '321-478', '324-446', '321-967', '320-678'],
 'bg': ['B+', 'A-', 'B+', 'O-', 'A-', 'B+']}

In [9]:
# Pass this Dictionary of Python Lists to pd.Dataframe()
df_people = pd.DataFrame(data=people)
df_people

name  age    address     cell  bg
0  Khursheed   52     Lahore  321-123  B+
1       Aqsa   51    Karachi  320-431  A-
2       Sana   26     Lahore  321-478  B+
3    Wajeeha   22  Islamabad  324-446  O-
4    Basirat   18      Kakul  321-967  A-
5        Hrm   17    Karachi  320-678  B+

- Note that column labels are set as per the keys inside the dictionary object, while the row labels/indices are set to default numerical values.
- You can set the row indices while creating the dataframe by passing the index argument to `pd.DataFrame()` method, or can do that later by assigning the new values to the `index` and `columns` attributes of a dataframe object.

In [10]:
# Let us change the row labels of above dataframe
row_labels = ['MS01', 'MS02', 'MS03', 'MS04', 'MS05', 'MS06']
df_people.index = row_labels
df_people

name  age    address     cell  bg
MS01  Khursheed   52     Lahore  321-123  B+
MS02       Aqsa   51    Karachi  320-431  A-
MS03       Sana   26     Lahore  321-478  B+
MS04    Wajeeha   22  Islamabad  324-446  O-
MS05    Basirat   18      Kakul  321-967  A-
MS06        Hrm   17    Karachi  320-678  B+

### d. Creating a Dataframe from Dictionary of Panda Series
One can think of a dataframe as a dictionary of Panda Series: 
- `Keys` are column names, and 
- `Values` are Series object for the respective columns.

In [11]:
dict = {
    "name": pd.Series(['Shifa', 'Aqsa', 'Aaraiz']),
    "age": pd.Series([50, 22, 18]),
    "addr": pd.Series(['Lahore', 'Islamabad','Karachi']),
}
df = pd.DataFrame(data=dict)
df

name  age       addr
0   Shifa   50     Lahore
1    Aqsa   22  Islamabad
2  Aaraiz   18    Karachi

>Note from the above output, that every series object becomes the data of the appropriate column. Moreover, the keys of the dictionary become the column labels.

In [12]:
import numpy as np 

In [13]:
dict = {
    "name": pd.Series(data=['Shifa', 'Abdul Ahad', 'Basirat', 'Aaraiz'], index=['a','b','c', 'd']),
    "age": pd.Series(data=[50, 22,np.nan, 18], index=['a','b','c','d']),
    "addr": pd.Series(data=['Lahore', '', 'Peshawer','Karachi'], index=['a','b','c', 'd']),
}
df = pd.DataFrame(dict)
df

name   age      addr
a       Shifa  50.0    Lahore
b  Abdul Ahad  22.0          
c     Basirat   NaN  Peshawer
d      Aaraiz  18.0   Karachi

>- In the above code and its output, note that every series object has four data values and four corresponding indices.
>- Also note that in the `age` series, we have a NaN value, and in the `addr` series we have an empty string.
>- Another point to note that the row indices of the three series exactly match, in number as well as in sequence/value.
>- A question arise, what if the indices of series are different. See the following code to understand this concept.

In [14]:
import pandas as pd
import numpy as np

In [15]:
dict = {
    "name": pd.Series(['Kiran', 'Aqsa', 'Aaraiz', 'Abdul Ahad'], index=['a','b','c', 'd']),
    "age": pd.Series([50, 22,np.nan, 18], index=['a','x','y','d']),
    "addr": pd.Series(['Lahore', '','Karachi'], index=['a', 'd', 'x']),
}
df = pd.DataFrame(dict)
df

name   age     addr
a       Kiran  50.0   Lahore
b        Aqsa   NaN      NaN
c      Aaraiz   NaN      NaN
d  Abdul Ahad  18.0         
x         NaN  22.0  Karachi
y         NaN   NaN      NaN

In [16]:
df.head(-4)

name   age    addr
a  Kiran  50.0  Lahore
b   Aqsa   NaN     NaN

In [17]:
df.tail()

name   age     addr
b        Aqsa   NaN      NaN
c      Aaraiz   NaN      NaN
d  Abdul Ahad  18.0         
x         NaN  22.0  Karachi
y         NaN   NaN      NaN

>- In the above code and its output, note that first series object has four data values and four corresponding indices. Similarly, second series object has four data values (with one `np.nan` value) and four corresponding indices, which are a bit different from the first series object. Third series has three data values (with one empty string) and three indices.
>- Note the resulting Dataframe has six rows and three columns.
    - For index 'a' we have value in all the three series objects or columns.
    - For index 'b' we have a value in first series object, and NaN for the second and third column, since the second and third series object has no value corresponding to row index 'b.

## 3. Attributes of Pandas Dataframe
- Like Series, we can access properties/attributes of a dataframe by using dot `.` notation

In [18]:
people = {
    "name" : ["Kiran", "Khursheed", "Aqsa", "Sana", "Basirat", "Hrm"],
    "age" : [52, 51, 26, 22, 18, 17],
    "address": ["Lahore", "Karachi", "Lahore", "Islamabad", "Kakul", "Karachi"],
    "cell" : ["321-123", "320-431", "321-478", "324-446", "321-967", "320-678"],
    "bg": ["B+", "A-", "B+", "O-", "A-", "B+"]
}

df_people = pd.DataFrame(data=people, index=['MS01', 'MS02', 'MS03', 'MS04', 'MS05', 'MS06'])
df_people

name  age    address     cell  bg
MS01      Kiran   52     Lahore  321-123  B+
MS02  Khursheed   51    Karachi  320-431  A-
MS03       Aqsa   26     Lahore  321-478  B+
MS04       Sana   22  Islamabad  324-446  O-
MS05    Basirat   18      Kakul  321-967  A-
MS06        Hrm   17    Karachi  320-678  B+

In [19]:
# `shape` attribute of a dataframe object return a two value tuple containing rows and columns
# Note the rows count does not include the column labels and column count does not include the row index
df_people.shape 

(6, 5)

In [20]:
# `ndim` attribute of a dataframe object returns number of dimensions (which is always 2)
df_people.ndim

2

In [21]:
# `size` attribute of a dataframe object returns the number of elements in the underlying data
df_people.size

30

In [22]:
# `index` attribute of a dataframe object return the list of row indices and its datatype
df_people.index

Index(['MS01', 'MS02', 'MS03', 'MS04', 'MS05', 'MS06'], dtype='object')

In [23]:
# `columns` attribute of a dataframe object return the list of column labels and its datatype
df_people.columns

Index(['name', 'age', 'address', 'cell', 'bg'], dtype='object')

In [24]:
#This attribute is used to fetch both index and column names.
df_people.axes

[Index(['MS01', 'MS02', 'MS03', 'MS04', 'MS05', 'MS06'], dtype='object'),
 Index(['name', 'age', 'address', 'cell', 'bg'], dtype='object')]

In [25]:
# `values` attribute of a dataframe object returns a NumPy 2-D having all the values in the DataFrame, 
# without the row indices and column labels
df_people.values

array([['Kiran', 52, 'Lahore', '321-123', 'B+'],
       ['Khursheed', 51, 'Karachi', '320-431', 'A-'],
       ['Aqsa', 26, 'Lahore', '321-478', 'B+'],
       ['Sana', 22, 'Islamabad', '324-446', 'O-'],
       ['Basirat', 18, 'Kakul', '321-967', 'A-'],
       ['Hrm', 17, 'Karachi', '320-678', 'B+']], dtype=object)

In [26]:
df.empty

False

In [27]:
# `dtypes` attribute of a dataframe object return the data type of each column in the dataframe
df_people.dtypes

name       object
age         int64
address    object
cell       object
bg         object
dtype: object

In [28]:
# To check number on non-NA values
df_people.count()

name       6
age        6
address    6
cell       6
bg         6
dtype: int64

# Bonus

#### The `df.info()` Method

In [29]:
#This method prints information about a DataFrame including the row indices, column labels, 
# non-null values count in each column, datatype and memory usage
df_people.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, MS01 to MS06
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   name     6 non-null      object
 1   age      6 non-null      int64 
 2   address  6 non-null      object
 3   cell     6 non-null      object
 4   bg       6 non-null      object
dtypes: int64(1), object(4)
memory usage: 288.0+ bytes
